### ISSUE TITLE
Slack Invite Link is invalid

### ISSUE THREAD

**Issue by x95** [YearOfProgramming/2017Challenges#133]

**Comment by lepmets** [comment]
"This invite link is no longer active."

**Comment by MJUIUC** [comment]
Thanks for letting us know!

**Comment by ASethi77** [comment]
Is this good to close?

**Comment by lepmets** [comment]
@ASethi77 The link hasn't been changed yet http://i.imgur.com/YCRnxPQ.png

**Comment by ASethi77** [comment]
@lepmets Thanks for pointing that out. I actually don't have straight write permissions to the repo yet but either me or another admin should be taking care of this soon.

**Comment by lepmets** [comment]
The new link lets you sign in but I still can't join the Slack channel.

**Comment by Fejolu** [comment]
![screen shot 2017-01-04 at 10 53 40](https://cloud.githubusercontent.com/assets/8938412/21638557/16ebdcf4-d26c-11e6-916d-c8d3054e3522.png)

**Comment by jarydremillard** [comment]
Hey guys! thanks for letting us know!
Here is a new link: https://yearofprogramming.slack.com/shared_invite/MTIzMTk1ODIwMzM5LTE0ODM1NDM1MjktYjU3M2FiMWI4Mw

**Comment by ASethi77** [comment]
Hi all,

We've set up a landing page for registration here: https://yearofprogramming.signup.team/ 
This should get rid of any issues regarding invite links being inactive. Please let us know if this works!

**Comment by ManuelMeraz** [comment]
https://yearofprogramming.signup.team/
