### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by qewbicle** [YearOfProgramming/2017Challenges#393]
I appreciate a license included. It is unclear if works submitted by others are covered by the license.  Maybe there should be some information on whether the current license can be extended to submitted code by placement of a copyright in the folder/file headers, or if others can or should include a License. I for one would like to get attribution if someone decides to post my solutions elsewhere other than this repository. For this reason I have not submitted them yet.  

There's a chance that some submitters beleive that they retain copyright with no licensing of their own provided, and others may conclude that the license you have provided with your own copyright covers their submitted work. Also, and more likely since there are new programmers challenging themselves, some have not considered that licensing and copyrights may apply.  

This repository seems to be laid out for beginners, and clarifying this will educate as well as avoid any future potential issues.

**Comment by ManuelMeraz** [comment]
@qewbicle I wouldn't submit solutions if you don't want other people copying your work without credit. I think whether or not a license protects you, there is a likely chance that someone will look at your work and copy some ideas from it. 

As to whether or not the license extends to your protection, I'm honestly not sure. I believe participation should be based on learning and sharing solutions/ideas and I always given credit to people's work so this hasn't really been a concern for me. 

I'll bring it up with some of the other admins and see what they think.

**Comment by qewbicle** [comment]
Hi, so in my looking around for an answer I've come to the conclusion that a license and a copyright are not the same things.  
A copyright is automatic when a person creates a work and a license is permission granted by the copyright holder, most usually the author, for others to use.   
There can be terms and conditions of a service where a contributor waives copyright or automatically falls within a license upon submission.  
Stack Exchange dealing with this situation 2015/2016  
[Getting user feedback/backlash for agreement to lose attribution with auto licensing](https://meta.stackexchange.com/questions/271080/the-mit-license-clarity-on-using-code-on-stack-overflow-and-stack-exchange)  
[Making decision to keep MIT Licensing on code posts without license to be posted, attribution required, and Creative Commons License on other texts/posts](https://meta.stackexchange.com/questions/272956/a-new-code-license-the-mit-this-time-with-attribution-required?cb=1)  
This means that the license provided can not be extended on to submitters works without a contributors agreement, alternatively, they can provide their own license.  
[https://choosealicense.com/no-license/](https://choosealicense.com/no-license/)  

By these measures, a license from the contributors protects you, not them.

**Comment by myrrlyn** [comment]
All submitters maintain copyright on their submissions. The project uses the MIT license as a blanket, which can be superseded by individual submissions, and these licenses apply to viewing and incorporating each other's work.

If you directly incorporate other's code in yours, it's considered good taste *at minimum* to reference their work by name, and comply with their license.

We cannot change the root license without every submitter agreeing to the change, and we cannot publish the repository under the group's name alone without every submitter ceding copyright. I anticipate neither of these things happening, so there shouldn't be a licensing or copyright issue.

On Jan 13, 2017 12:38, Qewbicle <notifications@github.com> wrote:

Hi, so in my looking around for an answer I've come to the conclusion that a license and a copyright are not the same things.
A copyright is automatic when a person creates a work and a license is permission granted by the copyright holder, most usually the author, for others to use.
There can be terms and conditions of a service where a contributor waives copyright or automatically falls within a license upon submission.
Stack Exchange dealing with this situation 2015/2016
Getting user feedback/backlash for agreement to lose attribution with auto licensing<https://meta.stackexchange.com/questions/271080/the-mit-license-clarity-on-using-code-on-stack-overflow-and-stack-exchange>
Making decision to keep MIT Licensing on code posts without license to be posted, attribution required, and Creative Commons License on other texts/posts<https://meta.stackexchange.com/questions/272956/a-new-code-license-the-mit-this-time-with-attribution-required?cb=1>
This means that the license provided can not be extended on to submitters works without a contributors agreement, alternatively, they can provide their own license.
https://choosealicense.com/no-license/

By these measures, a license from the contributors protects you, not them.

**Comment by qewbicle** [comment]
Here's a link to the terms of service of Github, specifically the copyright section.  
[https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership)

**Comment by qewbicle** [comment]
I found this.  
Copyright License Agreement  
[https://cla.github.com/](https://cla.github.com/)  

A rationale on a CLA from  Wikipedia  
[https://en.wikipedia.org/wiki/Contributor_License_Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement)

>The purpose of a CLA is to ensure that the guardian of a project's outputs has the necessary ownership or grants of rights over all contributions to allow them to distribute under the chosen licence. In some cases this will mean that the contributor will assign the copyright in all contributions to the project owner; in other cases, they will grant an irrevocable licence to allow the project maintainer to use the contribution. CLAs also have roles in raising awareness of IPR issues within a project

**Comment by qewbicle** [comment]
Here is a CLA generator.  
No https available for link  
[http://selector.harmonyagreements.org/](http://selector.harmonyagreements.org/)
